add_test([=[Pack5.RoundTrip_Simple]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack5.RoundTrip_Simple]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack5.RoundTrip_Simple]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pack5.RoundTrip_AllZeros]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack5.RoundTrip_AllZeros]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack5.RoundTrip_AllZeros]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pack5.RoundTrip_Exhaustive_59049]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack5.RoundTrip_Exhaustive_59049]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack5.RoundTrip_Exhaustive_59049]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pack10.RoundTrip_Simple]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack10.RoundTrip_Simple]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack10.RoundTrip_Simple]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pack10.RoundTrip_AllZeros]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack10.RoundTrip_AllZeros]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack10.RoundTrip_AllZeros]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pack10.RoundTrip_SampledPatterns]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack10.RoundTrip_SampledPatterns]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack10.RoundTrip_SampledPatterns]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pack20.RoundTrip_Simple]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack20.RoundTrip_Simple]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack20.RoundTrip_Simple]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pack20.RoundTrip_AllZeros]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack20.RoundTrip_AllZeros]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack20.RoundTrip_AllZeros]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Pack20.RoundTrip_SampledPatterns]=]  /home/runner/work/DualTrits/DualTrits/_codeql_build_dir/packing_tests [==[--gtest_filter=Pack20.RoundTrip_SampledPatterns]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Pack20.RoundTrip_SampledPatterns]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DualTrits/DualTrits/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  packing_tests_TESTS Pack5.RoundTrip_Simple Pack5.RoundTrip_AllZeros Pack5.RoundTrip_Exhaustive_59049 Pack10.RoundTrip_Simple Pack10.RoundTrip_AllZeros Pack10.RoundTrip_SampledPatterns Pack20.RoundTrip_Simple Pack20.RoundTrip_AllZeros Pack20.RoundTrip_SampledPatterns)
